# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tradingnode2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import trdb2py.trading2_pb2 as trading2__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tradingnode2.proto',
  package='tradingpb',
  syntax='proto3',
  serialized_options=b'Z&github.com/zhs007/tradingdb2/tradingpb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12tradingnode2.proto\x12\ttradingpb\x1a\x0etrading2.proto\"F\n\x11RequestServerInfo\x12\x31\n\x0c\x62\x61sicRequest\x18\x01 \x01(\x0b\x32\x1b.tradingpb.BasicRequestData\"?\n\x0fReplyServerInfo\x12,\n\x08nodeInfo\x18\x01 \x01(\x0b\x32\x1a.tradingpb.TradingNodeInfo\"p\n\x0eRequestCalcPNL\x12\x31\n\x0c\x62\x61sicRequest\x18\x01 \x01(\x0b\x32\x1b.tradingpb.BasicRequestData\x12+\n\x06params\x18\x02 \x01(\x0b\x32\x1b.tradingpb.SimTradingParams\"q\n\x0cReplyCalcPNL\x12,\n\x08nodeInfo\x18\x01 \x01(\x0b\x32\x1a.tradingpb.TradingNodeInfo\x12\x1f\n\x03pnl\x18\x02 \x03(\x0b\x32\x12.tradingpb.PNLData\x12\x12\n\nrunSeconds\x18\x03 \x01(\x03\x32\x9c\x01\n\x0cTradingNode2\x12K\n\rgetServerInfo\x12\x1c.tradingpb.RequestServerInfo\x1a\x1a.tradingpb.ReplyServerInfo\"\x00\x12?\n\x07\x63\x61lcPNL\x12\x19.tradingpb.RequestCalcPNL\x1a\x17.tradingpb.ReplyCalcPNL\"\x00\x42(Z&github.com/zhs007/tradingdb2/tradingpbb\x06proto3'
  ,
  dependencies=[trading2__pb2.DESCRIPTOR,])




_REQUESTSERVERINFO = _descriptor.Descriptor(
  name='RequestServerInfo',
  full_name='tradingpb.RequestServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='basicRequest', full_name='tradingpb.RequestServerInfo.basicRequest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=119,
)


_REPLYSERVERINFO = _descriptor.Descriptor(
  name='ReplyServerInfo',
  full_name='tradingpb.ReplyServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeInfo', full_name='tradingpb.ReplyServerInfo.nodeInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=184,
)


_REQUESTCALCPNL = _descriptor.Descriptor(
  name='RequestCalcPNL',
  full_name='tradingpb.RequestCalcPNL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='basicRequest', full_name='tradingpb.RequestCalcPNL.basicRequest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='tradingpb.RequestCalcPNL.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=298,
)


_REPLYCALCPNL = _descriptor.Descriptor(
  name='ReplyCalcPNL',
  full_name='tradingpb.ReplyCalcPNL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeInfo', full_name='tradingpb.ReplyCalcPNL.nodeInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pnl', full_name='tradingpb.ReplyCalcPNL.pnl', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='runSeconds', full_name='tradingpb.ReplyCalcPNL.runSeconds', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=413,
)

_REQUESTSERVERINFO.fields_by_name['basicRequest'].message_type = trading2__pb2._BASICREQUESTDATA
_REPLYSERVERINFO.fields_by_name['nodeInfo'].message_type = trading2__pb2._TRADINGNODEINFO
_REQUESTCALCPNL.fields_by_name['basicRequest'].message_type = trading2__pb2._BASICREQUESTDATA
_REQUESTCALCPNL.fields_by_name['params'].message_type = trading2__pb2._SIMTRADINGPARAMS
_REPLYCALCPNL.fields_by_name['nodeInfo'].message_type = trading2__pb2._TRADINGNODEINFO
_REPLYCALCPNL.fields_by_name['pnl'].message_type = trading2__pb2._PNLDATA
DESCRIPTOR.message_types_by_name['RequestServerInfo'] = _REQUESTSERVERINFO
DESCRIPTOR.message_types_by_name['ReplyServerInfo'] = _REPLYSERVERINFO
DESCRIPTOR.message_types_by_name['RequestCalcPNL'] = _REQUESTCALCPNL
DESCRIPTOR.message_types_by_name['ReplyCalcPNL'] = _REPLYCALCPNL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestServerInfo = _reflection.GeneratedProtocolMessageType('RequestServerInfo', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSERVERINFO,
  '__module__' : 'tradingnode2_pb2'
  # @@protoc_insertion_point(class_scope:tradingpb.RequestServerInfo)
  })
_sym_db.RegisterMessage(RequestServerInfo)

ReplyServerInfo = _reflection.GeneratedProtocolMessageType('ReplyServerInfo', (_message.Message,), {
  'DESCRIPTOR' : _REPLYSERVERINFO,
  '__module__' : 'tradingnode2_pb2'
  # @@protoc_insertion_point(class_scope:tradingpb.ReplyServerInfo)
  })
_sym_db.RegisterMessage(ReplyServerInfo)

RequestCalcPNL = _reflection.GeneratedProtocolMessageType('RequestCalcPNL', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCALCPNL,
  '__module__' : 'tradingnode2_pb2'
  # @@protoc_insertion_point(class_scope:tradingpb.RequestCalcPNL)
  })
_sym_db.RegisterMessage(RequestCalcPNL)

ReplyCalcPNL = _reflection.GeneratedProtocolMessageType('ReplyCalcPNL', (_message.Message,), {
  'DESCRIPTOR' : _REPLYCALCPNL,
  '__module__' : 'tradingnode2_pb2'
  # @@protoc_insertion_point(class_scope:tradingpb.ReplyCalcPNL)
  })
_sym_db.RegisterMessage(ReplyCalcPNL)


DESCRIPTOR._options = None

_TRADINGNODE2 = _descriptor.ServiceDescriptor(
  name='TradingNode2',
  full_name='tradingpb.TradingNode2',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=416,
  serialized_end=572,
  methods=[
  _descriptor.MethodDescriptor(
    name='getServerInfo',
    full_name='tradingpb.TradingNode2.getServerInfo',
    index=0,
    containing_service=None,
    input_type=_REQUESTSERVERINFO,
    output_type=_REPLYSERVERINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='calcPNL',
    full_name='tradingpb.TradingNode2.calcPNL',
    index=1,
    containing_service=None,
    input_type=_REQUESTCALCPNL,
    output_type=_REPLYCALCPNL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRADINGNODE2)

DESCRIPTOR.services_by_name['TradingNode2'] = _TRADINGNODE2

# @@protoc_insertion_point(module_scope)
